server:
  port: 8202  #服务端口号


spring:
  application:
    name: service-cmn #服务名

  profiles:
    active: dev
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 437101.sl
    driver-class-name: com.mysql.cj.jdbc.Driver

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8858

  redis:
    host: 121.43.154.153
    password: 437101.Sl

#  #mongodb地址
  data:
    mongodb:
      uri: mongodb://121.43.154.153:27017/yygh_hosp

#mybatis-plus
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:**/*Mapper.xml


##开启sentinel
feign:
  sentinel:
    enabled: true






