# 服务端口
server:
  port: 8024

# 服务名
spring:
  application:
    name: service-msm

  profiles:
    active: dev

  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_user?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 437101.sl
    driver-class-name: com.mysql.cj.jdbc.Driver

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 121.43.154.153
    password: 437101.Sl

  rabbitmq:
    host: 121.43.154.153
    port: 5672
    username: guest
    password: guest

aliyun:
  sms:
    regionId: default
    accessKeyID: LTAI5tFD6c1ZpmbETk5egnP6
    accessKeySecret: fL5YVfG93ED2VYiYY1Yk11b6OwK0H8



