server:
  port: 8207

spring:
  application:
    name: service-task

  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: 121.43.154.153
    port: 5672
    username: guest
    password: guest
