server:
  port: 8206


spring:
  application:
    name: service-order

  profiles:
    active: dev

    #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 437101.sl
    driver-class-name: com.mysql.cj.jdbc.Driver

    #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  data:
    mongodb:
      host: 121.43.154.153
      port: 27017
      database: yygh_hosp
      authentication-database: admin
      username: root
      password: 123456.sl

  rabbitmq:
    host: 121.43.154.153
    port: 5672
    username: guest
    password: guest

  redis:
    host: 121.43.154.153
    password: 437101.Sl
weixin:

#关联的公众号appid
  appid: wx74862e0dfcf69954
  #商户号
  partner: 1558950191
  #商户key
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #退款证书
  cert: C:\\Users\\13192\\IdeaProjects\\yygh_parent\\service\\service_order\\src\\main\\resources\\cert\\apiclient_cert.p12