# 服务端口
server:
  port: 80
# 服务名
spring:
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates: Path=/*/hosp/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates: Path=/*/cmn/**

        - id: service-user
          uri: lb://service-user
          predicates: Path=/*/user/**

        - id: service-msm
          uri: lb://service-msm
          predicates: Path=/*/msm/**


